---
abstract: 'A Catmandu::Serializer backend using Data::MessagePack'
author:
  - 'Nicolas Steenlant <nicolas.steenlant@ugent.be>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.42
dynamic_config: 1
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-Serializer-messagepack
provides:
  Catmandu::Serializer::messagepack:
    file: lib/Catmandu/Serializer/messagepack.pm
    version: 0.0101
requires:
  Catmandu: 0.8006
  Data::MessagePack: 0.39
  MIME::Base64: 0
  perl: v5.10.1
resources:
  bugtracker: https://github.com/LibreCat/Catmandu-Serializer-messagepack/issues
  homepage: https://github.com/LibreCat/Catmandu-Serializer-messagepack
  license: http://dev.perl.org/licenses/
  repository: https://github.com/LibreCat/Catmandu-Serializer-messagepack.git
version: 0.0101
